/**
 * Data access for client review links. Reviews live in their own table
 * (`article_reviews`) holding a snapshot of the article as it was sent — the
 * client approves exactly what they saw, and a client's response never has to
 * be merged into the agent's seo_clients row (which the browser overwrites
 * wholesale on every save).
 */
const base = (env) => env.VITE_SUPABASE_URL.trim().replace(/\/$/, "");
const headers = (env) => ({
  "Content-Type": "application/json",
  apikey: env.VITE_SUPABASE_ANON_KEY,
  Authorization: "Bearer " + env.VITE_SUPABASE_ANON_KEY,
});

// Tokens are 36 hex chars generated by the agent — reject anything else before
// it reaches a query string.
export const validToken = (t) => /^[a-f0-9]{36}$/.test(t || "");

export async function getReview(env, token) {
  const res = await fetch(
    `${base(env)}/rest/v1/article_reviews?token=eq.${token}&select=*`,
    { headers: headers(env) }
  );
  if (!res.ok) throw new Error("Failed to read review: HTTP " + res.status);
  const rows = await res.json();
  return rows[0] || null;
}

export async function respondToReview(env, token, status, comment) {
  const res = await fetch(`${base(env)}/rest/v1/article_reviews?token=eq.${token}`, {
    method: "PATCH",
    headers: { ...headers(env), Prefer: "return=minimal" },
    body: JSON.stringify({ status, comment: comment || null, responded_at: new Date().toISOString() }),
  });
  if (!res.ok) throw new Error("Failed to save response: HTTP " + res.status);
}
